default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV.fetch('MYSQL_HOST') { 'db' } %>

development:
  <<: *default
  database: <%= ENV['PROJECT_NAME'] %>_development

test:
  <<: *default
  database: <%= ENV['PROJECT_NAME'] %>_test

production:
  <<: *default
  database: <%= ENV['PROJECT_NAME'] %>_production
  username: <%= ENV['PROJECT_NAME'] %>
  password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>