version: "3"

services:
  mysql:
    image: mysql:8.0.21
    volumes:
      - D:\programming\docker\volumes\ruby\practice_0421/mysql_data:/var/lib/mysql # データの永続化
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PROJECT_NAME}_development
      MYSQL_USER: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    container_name: ${MYSQL_HOST}_${PROJECT_NAME}
    ports:
        - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password # 認証方式を8系以前のものにする。
  ruby:
    depends_on:
      - mysql
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - D:\programming\docker\volumes\ruby\practice_0421:/project
    links:
      - mysql
    tty: true
    env_file: .env
volumes:
  new_rails:
    driver: local