version: "3"

services:
  db:
    image: mysql:8.0.21
    volumes:
      - ./project/mysql_data:/var/lib/mysql # データの永続化
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      MYSQL_DATABASE: ${PROJECT_NAME}_development
    ports:
        - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password # 認証方式を8系以前のものにする。
  ruby:
    depends_on:
      - db
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./project:/project
    links:
      - db
    tty: true
    env_file: .env
volumes:
  new_rails:
    driver: local